# remote_theme: pages-themes/cayman@v0.2.0
# plugins:
# - jekyll-remote-theme # add this line to the plugins list if you already have one
# title: [For the Love of Data science💛]
# description: [I am documenting my journey of data science here, Connect @linkedin]

title: Shyam Gupta
logo: /assets/css/img/PXL_20231006_091947610.MP.jpg
description: Passionate learner | Curious & Excited for AI Era 
# show_downloads: true
theme: jekyll-theme-minimal
